import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('heAtwCBAZBBBxwfAaCKAfCYBNBhAMDACBEDRAGJAACEFACBBBACAFCDEEpsAXAvzBeFmWVg-DfB4NRiAAADAjSAAA4NTAhUAhGABBABBBDALAAAGAhAADBHAGAbADAEAACGAlTBYAYAeAYAeAYAeAYAeAYAHBgx');
